; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

song_Start
song_StartDisarkGenerateExternalLabel

song_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
song_DisarkByteRegionEnd0
song_DisarkPointerRegionStart1
	dw song_FmInstrumentTable
	dw song_ArpeggioTable
	dw song_PitchTable
; Table of the Subsongs.
	dw song_Subsong0
song_DisarkPointerRegionEnd1

; The Arpeggio table.
song_ArpeggioTable
song_DisarkWordRegionStart2
	dw 0
song_DisarkWordRegionEnd2
song_DisarkPointerRegionStart3
song_DisarkPointerRegionEnd3

; The Pitch table.
song_PitchTable
song_DisarkWordRegionStart4
	dw 0
song_DisarkWordRegionEnd4
song_DisarkPointerRegionStart5
song_DisarkPointerRegionEnd5

; The FM Instrument table.
song_FmInstrumentTable
song_DisarkPointerRegionStart6
	dw song_FmInstrument0
	dw song_FmInstrument1
	dw song_FmInstrument2
	dw song_FmInstrument3
	dw song_FmInstrument4
song_DisarkPointerRegionEnd6

song_DisarkByteRegionStart7
song_FmInstrument0
	db 255	; Speed.

song_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
song_DisarkPointerRegionStart8
	dw song_FmInstrument0Loop	; Loops.
song_DisarkPointerRegionEnd8

song_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
song_DisarkPointerRegionStart9
	dw song_FmInstrument0Loop	; Loop to silence.
song_DisarkPointerRegionEnd9

song_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 24	; Arpeggio: 12.

	db 189	; Volume: 15.
	db 26	; Arpeggio: 13.

	db 189	; Volume: 15.
	db 32	; Arpeggio: 16.

	db 189	; Volume: 15.
	db 14	; Arpeggio: 7.

	db 4	; End the instrument.
song_DisarkPointerRegionStart10
	dw song_FmInstrument0Loop	; Loop to silence.
song_DisarkPointerRegionEnd10

song_FmInstrument3
	db 0	; Speed.

song_FmInstrument3Loop	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 0	; Volume: 0.

	db 4	; End the instrument.
song_DisarkPointerRegionStart11
	dw song_FmInstrument3Loop	; Loops.
song_DisarkPointerRegionEnd11

song_FmInstrument4
	db 1	; Speed.

	db 125	; Volume: 15.
	dw 16	; Pitch: 16.

	db 61	; Volume: 15.

song_FmInstrument4Loop	db 61	; Volume: 15.

	db 125	; Volume: 15.
	dw -1	; Pitch: -1.

	db 4	; End the instrument.
song_DisarkPointerRegionStart12
	dw song_FmInstrument4Loop	; Loops.
song_DisarkPointerRegionEnd12

song_DisarkByteRegionEnd7
song_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

song_Subsong0
	db 3	; Initial speed.

; The Linker.
; Pattern 0
song_Subsong0loop
	db 5	; State byte.
	db 47	; New height.
song_Subsong0DisarkPointerRegionStart1
	dw song_Subsong0_Track0, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart2
	dw song_Subsong0_Track2, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart3
	dw song_Subsong0_Track3, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart4
	dw song_Subsong0_Track4, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart5
	dw song_Subsong0_Track0, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart6
	dw song_Subsong0_Track2, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart7
	dw song_Subsong0_Track5, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart8
	dw song_Subsong0_Track6, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart9
	dw song_Subsong0_Track7, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart10
	dw song_Subsong0_Track8, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart11
	dw song_Subsong0_Track9, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart12
	dw song_Subsong0_Track10, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart13
	dw song_Subsong0_Track7, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart14
	dw song_Subsong0_Track8, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd14
; The tracks.

; Pattern 14
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart15
	dw song_Subsong0_Track11, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd15
; The tracks.

; Pattern 15
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart16
	dw song_Subsong0_Track12, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd16
; The tracks.

; Pattern 16
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart17
	dw song_Subsong0_Track13, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd17
; The tracks.

; Pattern 17
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart18
	dw song_Subsong0_Track14, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd18
; The tracks.

; Pattern 18
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart19
	dw song_Subsong0_Track15, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd19
; The tracks.

; Pattern 19
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart20
	dw song_Subsong0_Track16, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd20
; The tracks.

; Pattern 20
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart21
	dw song_Subsong0_Track13, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd21
; The tracks.

; Pattern 21
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart22
	dw song_Subsong0_Track14, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd22
; The tracks.

; Pattern 22
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart23
	dw song_Subsong0_Track17, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd23
; The tracks.

; Pattern 23
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart24
	dw song_Subsong0_Track18, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd24
; The tracks.

; Pattern 24
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart25
	dw song_Subsong0_Track19, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd25
; The tracks.

; Pattern 25
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart26
	dw song_Subsong0_Track20, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd26
; The tracks.

; Pattern 26
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart27
	dw song_Subsong0_Track21, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd27
; The tracks.

; Pattern 27
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart28
	dw song_Subsong0_Track22, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd28
; The tracks.

; Pattern 28
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart29
	dw song_Subsong0_Track19, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd29
; The tracks.

; Pattern 29
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart30
	dw song_Subsong0_Track20, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd30
; The tracks.

; Pattern 30
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart31
	dw song_Subsong0_Track23, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd31
; The tracks.

; Pattern 31
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart32
	dw song_Subsong0_Track24, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd32
; The tracks.

; Pattern 32
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart33
	dw song_Subsong0_Track13, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd33
; The tracks.

; Pattern 33
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart34
	dw song_Subsong0_Track14, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd34
; The tracks.

; Pattern 34
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart35
	dw song_Subsong0_Track15, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd35
; The tracks.

; Pattern 35
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart36
	dw song_Subsong0_Track16, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd36
; The tracks.

; Pattern 36
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart37
	dw song_Subsong0_Track13, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd37
; The tracks.

; Pattern 37
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart38
	dw song_Subsong0_Track14, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd38
; The tracks.

; Pattern 38
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart39
	dw song_Subsong0_Track17, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd39
; The tracks.

; Pattern 39
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart40
	dw song_Subsong0_Track18, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd40
; The tracks.

	db 0	; End of the subsong.
song_Subsong0DisarkPointerRegionStart41
	dw song_Subsong0loop
song_Subsong0DisarkPointerRegionEnd41

; The Tracks.
song_Subsong0_Track0
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 61, 4	; Long wait: 5.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 12	; Note: 36.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track1
	db 61, 47	; Long wait: 48.


song_Subsong0_Track2
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 17	; Note: 41.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 17	; Note: 41.
	db 62	; Short wait: 1.

	db 9	; Note: 33.
	db 61, 4	; Long wait: 5.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 9	; Note: 33.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 15	; Note: 39.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 12	; Note: 36.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track3
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 61, 4	; Long wait: 5.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 22	; Note: 46.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 15	; Note: 39.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track4
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 21	; Note: 45.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 21	; Note: 45.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 61, 4	; Long wait: 5.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 15	; Note: 39.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 12	; Note: 36.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 24	; Note: 48.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track5
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 61, 4	; Long wait: 5.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 15	; Note: 39.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 22	; Note: 46.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 15	; Note: 39.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track6
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 61, 4	; Long wait: 5.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 19	; Note: 43.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 12	; Note: 36.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 24	; Note: 48.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track7
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 29	; Note: 53.
	db 126	; Short wait: 2.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track8
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 17	; Note: 41.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 17	; Note: 41.
	db 62	; Short wait: 1.

	db 9	; Note: 33.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 22	; Note: 46.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 147	; Note: 43.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 15	; Note: 39.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 8	; Note: 32.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 12	; Note: 36.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track9
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 22	; Note: 46.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track10
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 21	; Note: 45.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 21	; Note: 45.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track11
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 29	; Note: 53.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 22	; Note: 46.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track12
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 29	; Note: 53.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 147	; Note: 43.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 24	; Note: 48.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track13
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 10	; Note: 34.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 22	; Note: 46.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track14
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 17	; Note: 41.
	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 17	; Note: 41.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 15	; Note: 39.
	db 155	; Note: 51.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 8	; Note: 32.
	db 150	; Note: 46.
	db 8	; New instrument: 4.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 12	; Note: 36.
	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track15
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 29	; Note: 53.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 22	; Note: 46.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track16
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 21	; Note: 45.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 21	; Note: 45.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 169	; Note: 65.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 24	; Note: 48.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track17
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 24	; Note: 48.
	db 169	; Note: 65.
	db 8	; New instrument: 4.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 22	; Note: 46.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track18
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 27	; Note: 51.
	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 8	; New instrument: 4.
	db 126	; Short wait: 2.

	db 39	; Note: 63.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 167	; Note: 63.
	db 8	; New instrument: 4.
	db 147	; Note: 43.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 12	; Note: 36.
	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track19
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 34	; Note: 58.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track20
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 17	; Note: 41.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 9	; Note: 33.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 15	; Note: 39.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 12	; Note: 36.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track21
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 22	; Note: 46.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 22	; Note: 46.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track22
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 21	; Note: 45.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 34	; Note: 58.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 149	; Note: 45.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track23
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 36	; Note: 60.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 159	; Note: 55.
	db 6	; New instrument: 3.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 22	; Note: 46.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 22	; Note: 46.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track24
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 24	; Note: 48.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 155	; Note: 51.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 254	; Short wait: 4.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 147	; Note: 43.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 22	; Note: 46.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 24	; Note: 48.
	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0DisarkByteRegionEnd0
